name: flu_test
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rive: ^0.10.3
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.3
  flutter_gen_runner: ^5.1.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/rive/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    # flutter_svg: true
    # flare_flutter: true
    rive: true
    # lottie: true
  assets:
    enabled: true